// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqBpACzSdQPWcd7Bkpheiy95O4w20vZQ4',
    appId: '1:234330222829:web:077ebb1ca34af1ba0edce4',
    messagingSenderId: '234330222829',
    projectId: 'intrn-data',
    authDomain: 'intrn-data.firebaseapp.com',
    storageBucket: 'intrn-data.firebasestorage.app',
    measurementId: 'G-9HK643G47P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2IrK_8jZK0roFp3o6siojalFikNbR4U',
    appId: '1:234330222829:android:341ff99ed60f65b10edce4',
    messagingSenderId: '234330222829',
    projectId: 'intrn-data',
    storageBucket: 'intrn-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBecRbiUZmIdVqAkD50wgXwN4KupmYXs',
    appId: '1:234330222829:ios:15cd72574a11a8f10edce4',
    messagingSenderId: '234330222829',
    projectId: 'intrn-data',
    storageBucket: 'intrn-data.firebasestorage.app',
    iosClientId: '234330222829-4ea42cn2qn2pp9ji903r3oig1ghgrg7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.intrn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBecRbiUZmIdVqAkD50wgXwN4KupmYXs',
    appId: '1:234330222829:ios:15cd72574a11a8f10edce4',
    messagingSenderId: '234330222829',
    projectId: 'intrn-data',
    storageBucket: 'intrn-data.firebasestorage.app',
    iosClientId: '234330222829-4ea42cn2qn2pp9ji903r3oig1ghgrg7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.intrn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqBpACzSdQPWcd7Bkpheiy95O4w20vZQ4',
    appId: '1:234330222829:web:8787242e9fb745d00edce4',
    messagingSenderId: '234330222829',
    projectId: 'intrn-data',
    authDomain: 'intrn-data.firebaseapp.com',
    storageBucket: 'intrn-data.firebasestorage.app',
    measurementId: 'G-X32Z7HDNBJ',
  );
}
